name: 6. Interact GitHub API

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: create-ticket-comment
        with:            
          result-encoding: string
          script: |
            const randomNumber = Math.floor(Math.random() * 100);
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting! Here\'s tick number for you: ' + randomNumber
            });

            return randomNumber;

      - name: Show ticket number
        run: echo "${{steps.create-ticket-comment.outputs.result}}"