name: 6. Grouping lines

on:
  push:
    paths:
      - .github/workflows/6-grouping-lines.yml
  workflow_dispatch:
    inputs:
      title:
        description: Top group title
        required: false
        default: "Manual Grouping Run"
      nested-levels:
        description: Depth of nested groups (0-5)
        required: false
        default: "2"
      items:
        description: Comma-separated list of items
        required: false
        default: "alpha,beta,gamma"
      warn-on:
        description: Item to warn on
        required: false
        default: "beta"

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Grouping showcase
        uses: ./grouping-lines
        with:
          title: ${{ github.event.inputs.title }}
          nested-levels: ${{ github.event.inputs['nested-levels'] }}
          items: ${{ github.event.inputs.items }}
          warn-on: ${{ github.event.inputs['warn-on'] }}
